name: Setup PHP & Composer
description: Checkout, setup PHP, cache and install Composer dependencies

inputs:
  coverage:
    description: 'Coverage driver (none, xdebug, pcov)'
    required: false
    default: 'none'
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_pgsql, zip, pdo
        tools: composer:v2
        coverage: ${{ inputs.coverage }}

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      shell: bash

    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: node_modules/
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install Node dependencies & build assets
      run: |
        npm ci
        npm run build
      shell: bash