services:
  postgres:
    image: postgres:15-alpine
    container_name: sharetrips_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sharetrips
      POSTGRES_USER: tripsadmin
      POSTGRES_PASSWORD: tripsadmin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: