<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260326191347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, seats_booked INT NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, trip_id INT NOT NULL, passenger_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E00CEDDEA5BC2E0E ON booking (trip_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE4502E565 ON booking (passenger_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDEA5BC2E0E4502E565 ON booking (trip_id, passenger_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, method VARCHAR(255) NOT NULL, booking_id INT NOT NULL, payer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6D28840D3301C60 ON payment (booking_id)');
        $this->addSql('CREATE INDEX IDX_6D28840DC17AD9A9 ON payment (payer_id)');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reason VARCHAR(150) NOT NULL, details TEXT DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, admin_note TEXT DEFAULT NULL, reporter_id INT NOT NULL, reported_id INT NOT NULL, booking_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('CREATE INDEX IDX_C42F778494BDEEB6 ON report (reported_id)');
        $this->addSql('CREATE INDEX IDX_C42F77843301C60 ON report (booking_id)');
        $this->addSql('CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, origin VARCHAR(100) NOT NULL, destination VARCHAR(100) NOT NULL, departure_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_seats INT NOT NULL, price_per_seat DOUBLE PRECISION NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, driver_id INT NOT NULL, vehicle_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7656F53BC3423909 ON trip (driver_id)');
        $this->addSql('CREATE INDEX IDX_7656F53B545317D1 ON trip (vehicle_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(50) DEFAULT NULL, last_name VARCHAR(50) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(20) NOT NULL, suspended_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, admin_note TEXT DEFAULT NULL, is_verified BOOLEAN NOT NULL, token_register VARCHAR(255) DEFAULT NULL, token_register_lifetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand VARCHAR(50) NOT NULL, model VARCHAR(50) NOT NULL, color VARCHAR(30) DEFAULT NULL, plate VARCHAR(20) NOT NULL, seats INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, usser_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1B80E486719ED75B ON vehicle (plate)');
        $this->addSql('CREATE INDEX IDX_1B80E486D840794C ON vehicle (usser_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEA5BC2E0E FOREIGN KEY (trip_id) REFERENCES trip (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE4502E565 FOREIGN KEY (passenger_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D3301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DC17AD9A9 FOREIGN KEY (payer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778494BDEEB6 FOREIGN KEY (reported_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F77843301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53BC3423909 FOREIGN KEY (driver_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486D840794C FOREIGN KEY (usser_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEA5BC2E0E');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE4502E565');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D3301C60');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DC17AD9A9');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F778494BDEEB6');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F77843301C60');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53BC3423909');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B545317D1');
        $this->addSql('ALTER TABLE vehicle DROP CONSTRAINT FK_1B80E486D840794C');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE report');
        $this->addSql('DROP TABLE trip');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
