name: CI - Share Trips

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: write

env:
  MAILER_FROM: "noreply@sharetrips.fr"
  MAILER_FROM_NAME: "ShareTrips"

jobs:
  #security-checker:
  #name: Security Checker
  #runs-on: ubuntu-latest
  #steps:
    #- uses: actions/checkout@v4
    #- uses: ./.github/actions/setup

    #- name: Run Composer Security Audit
      #run: composer audit --no-dev

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    #needs: security-checker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run PHPCS
        run: vendor/bin/phpcs

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    #needs: security-checker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

  twig-lint:
    name: Twig Lint
    runs-on: ubuntu-latest
    #needs: security-checker
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run Twig Lint
        run: php bin/console lint:twig ./templates

  phpunit-unit:
    name: PHPUnit Unit Tests
    runs-on: ubuntu-latest
    needs: [phpcs, phpstan, twig-lint]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: vendor/bin/phpunit